const mtDesc = [
  {
    name: 'Mt. Washington',
    image: 'hiking-images/Mt. Washington.jpeg',
    elevation: '6288ft',
    shortDescription: 'Some brief description of Mt. Washington.',
    trails: ['Trail1 (6 miles)', 'Trail2 (12 miles)'],
    timeToComplete: '6hrs',
    somethingILearned: 'Something you learned about Mt. Washington.',
  },
  {
    name: 'Mt. Adams',
    image: 'hiking-images/Mt. Adams.jpeg',
    elevation: '4200ft',
    shortDescription:
      'It was a moderately difficult mountain to summit, the weather conditions were severe with inclement temperatures ranging from 5 - 10 degrees F.',
    trails: ['Trail1 (6 miles)', 'Trail2 (12 miles)'],
    timeToComplete: '6hrs',
    somethingILearned: 'Something you learned about Mt. Adams.',
  },
  {
    name: 'Mt. Monroe',
    image: 'hiking-images/Mt. Monroe.jpeg',
    elevation: '5372ft',
    shortDescription: 'Mt. Monroe short description here.',
    trails: ['Monroe Trail (4 miles)', 'Another Trail (10 miles)'],
    timeToComplete: '5hrs',
    somethingILearned: 'Something you learned about Mt. Monroe.',
  },
  {
    name: 'Mt. Madison',
    image: 'hiking-images/Mt. Madison.jpeg',
    elevation: '5366ft',
    shortDescription: 'Mt. Madison short description here.',
    trails: ['Madison Trail (5 miles)', 'Madison Loop (8 miles)'],
    timeToComplete: '7hrs',
    somethingILearned: 'Something you learned about Mt. Madison.',
  },
  {
    name: 'Mt. Lafayette',
    image: 'hiking-images/Mt. Lafayette.jpeg',
    elevation: '5260ft',
    shortDescription: 'Mt. Lafayette short description here.',
    trails: ['Lafayette Trail (7 miles)', 'Lafayette Loop (11 miles)'],
    timeToComplete: '8hrs',
    somethingILearned: 'Something you learned about Mt. Lafayette.',
  },
  {
    name: 'Mt. Lincoln',
    image: 'hiking-images/Mt. Lincoln.jpeg',
    elevation: '5089ft',
    shortDescription: 'Mt. Lincoln short description here.',
    trails: ['Lincoln Trail (4 miles)', 'Lincoln Loop (10 miles)'],
    timeToComplete: '6hrs',
    somethingILearned: 'Something you learned about Mt. Lincoln.',
  },
  {
    name: 'Mt. South Twin',
    image: 'hiking-images/Mt. South Twin.jpg',
    elevation: '4902ft',
    shortDescription: 'Mt. South Twin short description here.',
    trails: ['South Twin Trail (6 miles)', 'South Twin Loop (12 miles)'],
    timeToComplete: '7hrs',
    somethingILearned: 'Something you learned about Mt. South Twin.',
  },
  {
    name: 'Mt. North Twin',
    image: 'hiking-images/Mt. North Twin.jpeg',
    elevation: '4761ft',
    shortDescription: 'Mt. North Twin short description here.',
    trails: ['North Twin Trail (5 miles)', 'North Twin Loop (10 miles)'],
    timeToComplete: '6hrs',
    somethingILearned: 'Something you learned about Mt. North Twin.',
  },
  {
    name: 'Mt. Garfield',
    image: 'hiking-images/Mt. Garfield.jpeg',
    elevation: '4500ft',
    shortDescription: 'Mt. Garfield short description here.',
    trails: ['Garfield Trail (4 miles)', 'Garfield Loop (8 miles)'],
    timeToComplete: '5hrs',
    somethingILearned: 'Something you learned about Mt. Garfield.',
  },
  {
    name: 'Mt. Liberty',
    image: 'hiking-images/Mt. Liberty.jpeg',
    elevation: '4459ft',
    shortDescription: 'Mt. Liberty short description here.',
    trails: ['Liberty Trail (5 miles)', 'Liberty Loop (9 miles)'],
    timeToComplete: '6hrs',
    somethingILearned: 'Something you learned about Mt. Liberty.',
  },
  {
    name: 'Mt. Flume',
    image: 'hiking-images/Mt. Flume.jpeg',
    elevation: '4328ft',
    shortDescription: 'Mt. Flume short description here.',
    trails: ['Flume Trail (4 miles)', 'Flume Loop (10 miles)'],
    timeToComplete: '7hrs',
    somethingILearned: 'Something you learned about Mt. Flume.',
  },
  {
    name: 'Mt. Galehead',
    image: 'hiking-images/Mt. Galehead.jpg',
    elevation: '4024ft',
    shortDescription: 'Mt. Galehead short description here.',
    trails: ['Galehead Trail (4 miles)', 'Galehead Loop (10 miles)'],
    timeToComplete: '6hrs',
    somethingILearned: 'Something you learned about Mt. Galehead.',
  },
    {
        name: 'Mt. Tacumseh',
        image: 'hiking-images/Mt. Tacumseh.jpeg',
        elevation: '4003ft',
        shortDescription: 'Mt. Tacumseh short description here.',
        trails: ['Tacumseh Trail (4 miles)', 'Tacumseh Loop (9 miles)'],
        timeToComplete: '5hrs',
        somethingILearned: 'Something you learned about Mt. Tacumseh.',
    },
];

export default mtDesc;
