/* eslint-disable quotes */
// const mtDesc = [
//   {
//     name: 'Mt. Washington',
//     image: 'hiking-images/Mt. Washington.jpeg',
//     elevation: '6288ft',
//     shortDescription: 'Some brief description of Mt. Washington.',
//     trails: ['Trail1 (6 miles)', 'Trail2 (12 miles)'],
//     timeToComplete: '6hrs',
//     somethingILearned: 'Something you learned about Mt. Washington.',
//   },
//   {
//     name: 'Mt. Adams',
//     image: 'hiking-images/Mt. Adams.jpeg',
//     elevation: '4200ft',
//     shortDescription:
//       'It was a moderately difficult mountain to summit, the weather conditions were severe with inclement temperatures ranging from 5 - 10 degrees F.',
//     trails: ['Trail1 (6 miles)', 'Trail2 (12 miles)'],
//     timeToComplete: '6hrs',
//     somethingILearned: 'Something you learned about Mt. Adams.',
//   },
//   {
//     name: 'Mt. Monroe',
//     image: 'hiking-images/Mt. Monroe.jpeg',
//     elevation: '5372ft',
//     shortDescription: 'Mt. Monroe short description here.',
//     trails: ['Monroe Trail (4 miles)', 'Another Trail (10 miles)'],
//     timeToComplete: '5hrs',
//     somethingILearned: 'Something you learned about Mt. Monroe.',
//   },
//   {
//     name: 'Mt. Madison',
//     image: 'hiking-images/Mt. Madison.jpeg',
//     elevation: '5366ft',
//     shortDescription: 'Mt. Madison short description here.',
//     trails: ['Madison Trail (5 miles)', 'Madison Loop (8 miles)'],
//     timeToComplete: '7hrs',
//     somethingILearned: 'Something you learned about Mt. Madison.',
//   },
//   {
//     name: 'Mt. Lafayette',
//     image: 'hiking-images/Mt. Lafayette.jpeg',
//     elevation: '5260ft',
//     shortDescription: 'Mt. Lafayette short description here.',
//     trails: ['Lafayette Trail (7 miles)', 'Lafayette Loop (11 miles)'],
//     timeToComplete: '8hrs',
//     somethingILearned: 'Something you learned about Mt. Lafayette.',
//   },
//   {
//     name: 'Mt. Lincoln',
//     image: 'hiking-images/Mt. Lincoln.jpeg',
//     elevation: '5089ft',
//     shortDescription: 'Mt. Lincoln short description here.',
//     trails: ['Lincoln Trail (4 miles)', 'Lincoln Loop (10 miles)'],
//     timeToComplete: '6hrs',
//     somethingILearned: 'Something you learned about Mt. Lincoln.',
//   },
//   {
//     name: 'Mt. South Twin',
//     image: 'hiking-images/Mt. South Twin.jpg',
//     elevation: '4902ft',
//     shortDescription: 'Mt. South Twin short description here.',
//     trails: ['South Twin Trail (6 miles)', 'South Twin Loop (12 miles)'],
//     timeToComplete: '7hrs',
//     somethingILearned: 'Something you learned about Mt. South Twin.',
//   },
//   {
//     name: 'Mt. North Twin',
//     image: 'hiking-images/Mt. North Twin.jpeg',
//     elevation: '4761ft',
//     shortDescription: 'Mt. North Twin short description here.',
//     trails: ['North Twin Trail (5 miles)', 'North Twin Loop (10 miles)'],
//     timeToComplete: '6hrs',
//     somethingILearned: 'Something you learned about Mt. North Twin.',
//   },
//   {
//     name: 'Mt. Garfield',
//     image: 'hiking-images/Mt. Garfield.jpeg',
//     elevation: '4500ft',
//     shortDescription: 'Mt. Garfield short description here.',
//     trails: ['Garfield Trail (4 miles)', 'Garfield Loop (8 miles)'],
//     timeToComplete: '5hrs',
//     somethingILearned: 'Something you learned about Mt. Garfield.',
//   },
//   {
//     name: 'Mt. Liberty',
//     image: 'hiking-images/Mt. Liberty.jpeg',
//     elevation: '4459ft',
//     shortDescription: 'Mt. Liberty short description here.',
//     trails: ['Liberty Trail (5 miles)', 'Liberty Loop (9 miles)'],
//     timeToComplete: '6hrs',
//     somethingILearned: 'Something you learned about Mt. Liberty.',
//   },
//   {
//     name: 'Mt. Flume',
//     image: 'hiking-images/Mt. Flume.jpeg',
//     elevation: '4328ft',
//     shortDescription: 'Mt. Flume short description here.',
//     trails: ['Flume Trail (4 miles)', 'Flume Loop (10 miles)'],
//     timeToComplete: '7hrs',
//     somethingILearned: 'Something you learned about Mt. Flume.',
//   },
//   {
//     name: 'Mt. Galehead',
//     image: 'hiking-images/Mt. Galehead.jpg',
//     elevation: '4024ft',
//     shortDescription: 'Mt. Galehead short description here.',
//     trails: ['Galehead Trail (4 miles)', 'Galehead Loop (10 miles)'],
//     timeToComplete: '6hrs',
//     somethingILearned: 'Something you learned about Mt. Galehead.',
//   },
//   {
//     name: 'Mt. Tacumseh',
//     image: 'hiking-images/Mt. Tacumseh.jpeg',
//     elevation: '4003ft',
//     shortDescription: 'Mt. Tacumseh short description here.',
//     trails: ['Tacumseh Trail (4 miles)', 'Tacumseh Loop (9 miles)'],
//     timeToComplete: '5hrs',
//     somethingILearned: 'Something you learned about Mt. Tacumseh.',
//   },
// ];

// export default mtDesc;
const mtDesc = [
  {
    name: 'Mt. Washington',
    image: 'hiking-images/Mt._Washington.jpg',
    elevation: '6288ft',
    shortDescription:
      'Mount Washington is the highest and most deadliest mountain in Northeast USA. To summit Mt. Washington I took the Ammonoosuc Ravine to Crawford Path Loop which goes from Mt. Monroe to Washington. On the trail you will find lots of waterfalls plus, there is a AMC Lakes of the Coulds Hut, where you can take some rest. It was a difficult hike but worth the view. At the top of Mt. Washington there is a museum which shows the Mt. Washington history',
    trails: ['Ammonoosuc Ravine Trail (5.27 miles)', 'Crawford Path Trail (4 miles)'],
    timeToComplete: '8.2 hrs',
    somethingILearned:
      'Mt. Washington has recorded Americas worst weather, Highest Wind Speed and Coldest Temperature.',
  },
  {
    name: 'Mt. Adams',
    image: 'hiking-images/Mt. Adams.jpeg',
    elevation: '4200ft',
    shortDescription:
      'Mt. Adams is 2nd highest summit out of 48 Four Thousand Footers. It was a pretty difficult hike with some ranges of steep elevation gains. The weather was decent, it got cloudy and rainy for some time but overall weather was good. I summited this mountain in July. On my way back I took rest in AMC Madison Spring Hut, the lake view from the hut was beautiful.',
    trails: ['Air Line Trail (8.7 miles)'],
    timeToComplete: '7 hrs',
    somethingILearned: '.',
  },
  {
    name: 'Mt. Monroe',
    image: 'hiking-images/Mt._Monroe.jpg',
    elevation: '5372ft',
    shortDescription:
      "Mount Monroe, with an elevation of 5,372 feet (1,637 meters), is a majestic peak in New Hampshire's White Mountains. It's known for its prominent role in the Presidential Range and offers hikers breathtaking vistas, including a panoramic perspective of the surrounding peaks and the Southern Presidential Range.",
    trails: ['Ammonoosuc Ravine Trail (5.27 miles)', 'Crawford Path Trail (4 miles)'],
    timeToComplete: '3.4 hrs',
    somethingILearned: ' ',
  },
  {
    name: 'Mt. Madison',
    image: 'hiking-images/Mt._Madison.jpg',
    elevation: '5366ft',
    shortDescription:
      "Mount Madison, is a striking summit in the Presidential Range of New Hampshire's White Mountains. Known for its challenging trails and alpine beauty, it offers hikers stunning views of the surrounding wilderness, making it a popular destination for outdoor enthusiasts and adventurers.",
    trails: ['Airline-Vally Way Loop Trail (7.7 miles)'],
    timeToComplete: '6.9 hrs',
    somethingILearned: ' ',
  },
  {
    name: 'Mt. Lafayette',
    image: 'hiking-images/Mt._Lafayette.jpg',
    elevation: '5260ft',
    shortDescription:
      "Mount Lafayette, is one of the most iconic peaks in New Hampshire's White Mountains. It is renowned for its sweeping vistas, including the stunning Franconia Ridge, making it a favorite among hikers and photographers seeking breathtaking views of the surrounding landscape.",
    trails: ['Falling Water Trail (10.4 miles)'],
    timeToComplete: '8.6 hrs',
    somethingILearned: ' ',
  },
  {
    name: 'Mt. Lincoln',
    image: 'hiking-images/Mt._Lincoln.jpg',
    elevation: '5089ft',
    shortDescription:
      "Mount Lincoln, is a prominent peak in New Hampshire's White Mountains, often traversed along the Franconia Ridge. It offers panoramic views and is a popular destination for hikers exploring the scenic trails of the region.",
    trails: ['Falling Water Trail (10.4 miles)'],
    timeToComplete: '8.6 hrs',
    somethingILearned: ' ',
  },
  {
    name: 'Mt. South Twin',
    image: 'hiking-images/Mt. South Twin.jpg',
    elevation: '4902ft',
    shortDescription: 'Mt. South Twin short description here.',
    trails: ['Gale River Trail (14.6 miles)'],
    timeToComplete: '13.8 hrs',
    somethingILearned: ' ',
  },
  {
    name: 'Mt. North Twin',
    image: 'hiking-images/Mt._North_Twin.jpg',
    elevation: '4761ft',
    shortDescription: 'Mt. North Twin short description here.',
    trails: ['Gale River Trail (14.6 miles)'],
    timeToComplete: '13.8 hrs',
    somethingILearned: 'Something you learned about Mt. North Twin.',
  },
  {
    name: 'Mt. Garfield',
    image: 'hiking-images/Mt. Garfield.jpeg',
    elevation: '4500ft',
    shortDescription:
      'Mount Garfield, is a prominent peak in the White Mountains of New Hampshire. Hikers are drawn to its rugged beauty, accessible trails, and spectacular vistas, including a stunning view of the Pemigewasset Wilderness from the summit.',
    trails: ['Mount Garfield Trail (9.6 miles)'],
    timeToComplete: '7.4 hrs',
    somethingILearned: ' ',
  },
  {
    name: 'Mt. Liberty',
    image: 'hiking-images/Mt. Liberty.jpeg',
    elevation: '4459ft',
    shortDescription:
      'Mt. Liberty was a tough hike. The trail after 2 miles become steep. When I started the hike weather was decent but 1 mile away from summit it started to snow. At the summit it was very windy. But the view was worth it. ',
    trails: ['Liberty Spring Trail (7.1 miles)'],
    timeToComplete: '7.5 hrs',
    somethingILearned: '',
  },
  {
    name: 'Mt. Flume',
    image: 'hiking-images/Mt. Flume.jpeg',
    elevation: '4328ft',
    shortDescription:
      'Mt. Flume was one of my most scariest hike of my life. I went on the hike in Winters, the trail was very slippery and snowy. My gloves, water, food, shoes, and jacket got frozen. The temperature was -22°F at the summit. I won’t recommended beginners to try this hike in winters. ',
    trails: ['Flume Slide Trail (8.5 miles)'],
    timeToComplete: '10.8 hrs',
    somethingILearned: 'Mt. Flume trail is among the most terrifying 15 trails in NH.',
  },
  {
    name: 'Mt. Galehead',
    image: 'hiking-images/Mt. Galehead.jpg',
    elevation: '4024ft',
    shortDescription:
      "Mount Galehead, is a remote and serene peak in the White Mountains of New Hampshire. It's a haven for hikers seeking a quieter and less-traveled trail, with its beautiful forested paths and a peaceful summit overlooking the Pemigewasset Wilderness.",
    trails: ['Gale River Trail (14.6 miles)'],
    timeToComplete: '13.8 hrs',
    somethingILearned: '',
  },
  {
    name: 'Mt. Tacumseh',
    image: 'hiking-images/Mt._Tacumseh.jpg',
    elevation: '4003ft',
    shortDescription:
      "Mt. Tecumseh, is the smallest of New Hampshire's 4,000-footers but offers a picturesque and accessible hiking experience. Located in the White Mountains, it provides a rewarding journey for hikers, with well-maintained trail and beautiful forested surroundings.",
    trails: ['Mount Tacumseh Trail (5.9 miles)'],
    timeToComplete: '5hrs',
    somethingILearned: 'Something you learned about Mt. Tacumseh.',
  },
];
export default mtDesc;
